### PR TITLE
[WIP] Remove unsafe array indexing by default

### PR DESCRIPTION
**Pull request by antoinewdg**
Related to #136. 
This is currently WIP because it should currently badly impact performance (I just removed the use of unsafe indexing by default). This PR is meant to be rebased with master regularly because parallelization should remove most of the places where unsafe indexing was necessary for performance reasons.

### CODE REVIEW

**Comment by antoinewdg** [comment]
## Comparing to master (e97e92a6)
using `--threshold 2, latest commit first`
<details><summary>0f501d68 Remove unsafe array indexing by default</summary>
  <p>





```bash

 name                                         e97e92a6.txt ns/iter     0f501d68.txt ns/iter     diff ns/iter  diff % 
 nacl::cache_move_particle_ewald              408,129 (+/- 1221)       488,967 (+/- 1122)             80,838  19.81% 
 nacl::energy_ewald                           618,673 (+/- 923)        696,935 (+/- 1026)             78,262  12.65% 
 nacl::forces_ewald                           17,193,319 (+/- 40173)   18,482,857 (+/- 47795)      1,289,538   7.50% 
 nacl::virial_ewald                           48,751,925 (+/- 463993)  50,652,497 (+/- 435405)     1,900,572   3.90% 
 propane::cache_move_all_rigid_molecules      1,029,772 (+/- 13137)    1,089,224 (+/- 16767)          59,452   5.77% 
 water::cache_move_all_rigid_molecules_ewald  8,431,895 (+/- 44897)    8,603,203 (+/- 181007)        171,308   2.03% 
 water::cache_move_particles_ewald            854,303 (+/- 1855)       966,000 (+/- 9068)            111,697  13.07% 
 water::energy_ewald                          1,015,895 (+/- 2737)     1,121,012 (+/- 2633)          105,117  10.35% 
 water::forces_ewald                          24,984,067 (+/- 37616)   26,702,238 (+/- 50483)      1,718,171   6.88% 
 water::forces_wolf                           1,017,720 (+/- 1645)     995,648 (+/- 1653)            -22,072  -2.17% 
 water::virial_ewald                          69,775,999 (+/- 446336)  72,953,635 (+/- 432046)     3,177,636   4.55% 



```



</p></details>

## Individual benchmarks

<details><summary>0f501d68 Remove unsafe array indexing by default</summary>
  <p>





```bash


running 4 tests
test argon::cache_move_particle ... bench:     244,134 ns/iter (+/- 3,316)
test argon::energy              ... bench:   1,841,528 ns/iter (+/- 4,118)
test argon::forces              ... bench:   2,363,541 ns/iter (+/- 3,155)
test argon::virial              ... bench:   2,702,803 ns/iter (+/- 4,059)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 8 tests
test nacl::cache_move_particle_ewald ... bench:     488,967 ns/iter (+/- 1,122)
test nacl::cache_move_particle_wolf  ... bench:     105,981 ns/iter (+/- 318)
test nacl::energy_ewald              ... bench:     696,935 ns/iter (+/- 1,026)
test nacl::energy_wolf               ... bench:     473,638 ns/iter (+/- 1,020)
test nacl::forces_ewald              ... bench:  18,482,857 ns/iter (+/- 47,795)
test nacl::forces_wolf               ... bench:     663,958 ns/iter (+/- 1,480)
test nacl::virial_ewald              ... bench:  50,652,497 ns/iter (+/- 435,405)
test nacl::virial_wolf               ... bench:     661,845 ns/iter (+/- 978)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured


running 5 tests
test propane::cache_move_all_rigid_molecules ... bench:   1,089,224 ns/iter (+/- 16,767)
test propane::cache_move_particles           ... bench:     282,417 ns/iter (+/- 11,265)
test propane::energy                         ... bench:   1,130,463 ns/iter (+/- 16,771)
test propane::forces                         ... bench:   1,380,343 ns/iter (+/- 11,289)
test propane::virial                         ... bench:   1,450,641 ns/iter (+/- 2,480)

test result: ok. 0 passed; 0 failed; 0 ignored; 5 measured


running 10 tests
test water::cache_move_all_rigid_molecules_ewald ... bench:   8,603,203 ns/iter (+/- 181,007)
test water::cache_move_all_rigid_molecules_wolf  ... bench:   8,118,020 ns/iter (+/- 185,296)
test water::cache_move_particles_ewald           ... bench:     966,000 ns/iter (+/- 9,068)
test water::cache_move_particles_wolf            ... bench:     484,059 ns/iter (+/- 6,919)
test water::energy_ewald                         ... bench:   1,121,012 ns/iter (+/- 2,633)
test water::energy_wolf                          ... bench:     731,169 ns/iter (+/- 5,055)
test water::forces_ewald                         ... bench:  26,702,238 ns/iter (+/- 50,483)
test water::forces_wolf                          ... bench:     995,648 ns/iter (+/- 1,653)
test water::virial_ewald                         ... bench:  72,953,635 ns/iter (+/- 432,046)
test water::virial_wolf                          ... bench:     995,402 ns/iter (+/- 3,592)

test result: ok. 0 passed; 0 failed; 0 ignored; 10 measured




```



</p></details>

<details><summary>e97e92a6 Adds rotation matrix as method of Matrix3.</summary>
  <p>





```bash


running 4 tests
test argon::cache_move_particle ... bench:     242,307 ns/iter (+/- 2,644)
test argon::energy              ... bench:   1,848,378 ns/iter (+/- 3,873)
test argon::forces              ... bench:   2,352,011 ns/iter (+/- 13,482)
test argon::virial              ... bench:   2,712,471 ns/iter (+/- 3,944)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 8 tests
test nacl::cache_move_particle_ewald ... bench:     408,129 ns/iter (+/- 1,221)
test nacl::cache_move_particle_wolf  ... bench:     106,020 ns/iter (+/- 338)
test nacl::energy_ewald              ... bench:     618,673 ns/iter (+/- 923)
test nacl::energy_wolf               ... bench:     478,156 ns/iter (+/- 1,546)
test nacl::forces_ewald              ... bench:  17,193,319 ns/iter (+/- 40,173)
test nacl::forces_wolf               ... bench:     665,780 ns/iter (+/- 1,266)
test nacl::virial_ewald              ... bench:  48,751,925 ns/iter (+/- 463,993)
test nacl::virial_wolf               ... bench:     662,364 ns/iter (+/- 2,503)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured


running 5 tests
test propane::cache_move_all_rigid_molecules ... bench:   1,029,772 ns/iter (+/- 13,137)
test propane::cache_move_particles           ... bench:     280,833 ns/iter (+/- 12,626)
test propane::energy                         ... bench:   1,111,278 ns/iter (+/- 2,178)
test propane::forces                         ... bench:   1,380,730 ns/iter (+/- 4,239)
test propane::virial                         ... bench:   1,443,037 ns/iter (+/- 2,067)

test result: ok. 0 passed; 0 failed; 0 ignored; 5 measured


running 10 tests
test water::cache_move_all_rigid_molecules_ewald ... bench:   8,431,895 ns/iter (+/- 44,897)
test water::cache_move_all_rigid_molecules_wolf  ... bench:   8,121,626 ns/iter (+/- 31,029)
test water::cache_move_particles_ewald           ... bench:     854,303 ns/iter (+/- 1,855)
test water::cache_move_particles_wolf            ... bench:     480,972 ns/iter (+/- 2,548)
test water::energy_ewald                         ... bench:   1,015,895 ns/iter (+/- 2,737)
test water::energy_wolf                          ... bench:     730,282 ns/iter (+/- 1,672)
test water::forces_ewald                         ... bench:  24,984,067 ns/iter (+/- 37,616)
test water::forces_wolf                          ... bench:   1,017,720 ns/iter (+/- 1,645)
test water::virial_ewald                         ... bench:  69,775,999 ns/iter (+/- 446,336)
test water::virial_wolf                          ... bench:     992,837 ns/iter (+/- 3,094)

test result: ok. 0 passed; 0 failed; 0 ignored; 10 measured




```



</p></details>

<br>**CPU**: Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz

**Comment by Luthaf** [comment]
> This PR is meant to be rebased with master regularly because parallelization should remove most of the places where unsafe indexing was necessary for performance reasons.

I disagree: having nice parallel performance does not means that serial performances should be neglected.

**Comment by antoinewdg** [comment]
> having nice parallel performance does not means that serial performances should be neglected

That's not what I meant. It's just that normally all performance critical code will be parallelized, and parallel code uses iterators so no more unsafe indexing :). There may still be some places where it happens, and there we will need to use unsafe indexing.

But yeah having the benchmarks run while limiting the number of cores to one should be interesting to be sure we do not regress in sequential performance.

**Comment by Luthaf** [comment]
Ok, great then! 😃

**Comment by Luthaf** [comment]
Now that all parallelisation PR are merged, here are the results I get with the following patch:

```patch
diff --git a/src/core/src/types/arrays.rs b/src/core/src/types/arrays.rs
index 34e13d36..b6851ae4 100644
--- a/src/core/src/types/arrays.rs
+++ b/src/core/src/types/arrays.rs
@@ -87,19 +87,13 @@ impl<T: Default> Array2<T> {
 impl<T> Index<(usize, usize)> for Array2<T> {
     type Output = T;
     fn index(&self, index: (usize, usize)) -> &T {
-        unsafe {
-            // ndarray does the check for us in debug builds
-            self.0.uget(index)
-        }
+        &self.0[index]
     }
 }
 
 impl<T> IndexMut<(usize, usize)> for Array2<T> {
     fn index_mut(&mut self, index: (usize, usize)) -> &mut T {
-        unsafe {
-            // ndarray does the check for us in debug builds
-            self.0.uget_mut(index)
-        }
+        &mut self.0[index]
     }
 }
 
@@ -198,19 +192,13 @@ impl<T> Array3<T> {
 impl<T> Index<(usize, usize, usize)> for Array3<T> {
     type Output = T;
     fn index(&self, index: (usize, usize, usize)) -> &T {
-        unsafe {
-            // ndarray does the check for us in debug builds
-            self.0.uget(index)
-        }
+        &self.0[index]
     }
 }
 
 impl<T> IndexMut<(usize, usize, usize)> for Array3<T> {
     fn index_mut(&mut self, index: (usize, usize, usize)) -> &mut T {
-        unsafe {
-            // ndarray does the check for us in debug builds
-            self.0.uget_mut(index)
-        }
+        &mut self.0[index]
     }
 }
```

```
$ cargo benchcmp --threshold=3 unsafe.log safe.log
 name                                     unsafe.log ns/iter  safe.log ns/iter  diff ns/iter   diff %  speedup 
 argon::cache_move_particle               69,392              59,070                 -10,322  -14.87%   x 1.17 
 argon::energy                            159,083             206,834                 47,751   30.02%   x 0.77 
 argon::forces                            305,645             359,684                 54,039   17.68%   x 0.85 
 argon::virial                            191,846             207,634                 15,788    8.23%   x 0.92 
 nacl::cache_move_particle_ewald          271,338             328,060                 56,722   20.90%   x 0.83 
 nacl::cache_move_particle_wolf           90,637              72,651                 -17,986  -19.84%   x 1.25 
 nacl::energy_ewald                       538,929             616,134                 77,205   14.33%   x 0.87 
 nacl::energy_wolf                        70,163              76,979                   6,816    9.71%   x 0.91 
 nacl::forces_ewald                       2,201,561           2,455,274              253,713   11.52%   x 0.90 
 nacl::forces_wolf                        179,140             168,106                -11,034   -6.16%   x 1.07 
 nacl::virial_ewald                       4,013,170           4,498,400              485,230   12.09%   x 0.89 
 nacl::virial_wolf                        74,896              80,179                   5,283    7.05%   x 0.93 
 propane::cache_move_all_rigid_molecules  1,061,533           1,220,650              159,117   14.99%   x 0.87 
 propane::cache_move_particles            282,357             336,587                 54,230   19.21%   x 0.84 
 propane::energy                          282,027             296,064                 14,037    4.98%   x 0.95 
 propane::forces                          487,144             458,933                -28,211   -5.79%   x 1.06 
 propane::virial                          158,968             143,310                -15,658   -9.85%   x 1.11 
 water::cache_move_particles_ewald        498,228             579,862                 81,634   16.38%   x 0.86 
 water::energy_ewald                      937,294             1,091,917              154,623   16.50%   x 0.86 
 water::energy_wolf                       88,036              92,137                   4,101    4.66%   x 0.96 
 water::forces_ewald                      3,265,983           3,539,125              273,142    8.36%   x 0.92 
 water::virial_ewald                      6,075,510           6,758,304              682,794   11.24%   x 0.90 
 water::virial_wolf                       103,293             106,807                  3,514    3.40%   x 0.97 
```

It looks like there is still a non negligible loss of performance (between 15 and 30%) due to bounds checking.

**Pull request closed without merging**
