### PR TITLE
[WIP] Script for running benchmarks automatically

### PR DESCRIPTION
**Pull request by antoinewdg**
This PR presents a script used to run the benchmarks automatically in for a PR.

```
$ python scripts/run-benchmarks.py --help
Usage: run-benchmarks.py [OPTIONS] OUTPUT_DIR

  Run the benchmarks.

  If --pr-id is set, runs the benchmarks from this PR. The number of commits
  to bench is either the number provided in the PR body using [lumol bench
  <n_commits>], or as a parameter to this script (in case of both the script
  parameter prevails). The benchmark results are saved in OUTPUT_DIR, and
  if a PR id have been set a comment is automatically added to it with the
  results of the PR.

Options:
  -n, --n-commits INTEGER  number of commits to benchmark
  -p, --pr-id INTEGER
  --help                   Show this message and exit.
```

The script is automatically run on PR on Travis CI, if the number of commits is set in the PR body using [lumol bench <n>].

[lumol bench 2]

### CODE REVIEW

**Comment by Luthaf** [comment]
Instead of the sudo image, you can use `pip install --user -r requirements.txt`.

**Comment by antoinewdg** [comment]
That's indeed better thanks !

**Comment by antoinewdg** [comment]
## Comparing to master (b974d52a)
using `--threshold 2, latest commit first`
## Individual benchmarks

<details><summary>b974d52a Make EnergyCache Send + Sync</summary>
  <p>





```bash


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf               ... bench:     473,930 ns/iter (+/- 13,660)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf                          ... bench:     732,107 ns/iter (+/- 14,214)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured




```



</p></details>

<br>**CPU**: Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz

**Comment by antoinewdg** [comment]
## Comparing to master (3e54b97f)
using `--threshold 2, latest commit first`
<details><summary>70c19663 Various fixes</summary>
  <p>





```bash

 name         3e54b97f.txt ns/iter  70c19663.txt ns/iter  diff ns/iter  diff % 
 energy_wolf  470,673 (+/- 20663)   498,274 (+/- 36929)         27,601   5.86% 
 energy_wolf  729,106 (+/- 41502)   747,823 (+/- 35518)         18,717   2.57% 



```



</p></details>

<details><summary>4893e83e Handle travis CI case inside the script</summary>
  <p>





```bash

 name         3e54b97f.txt ns/iter  4893e83e.txt ns/iter  diff ns/iter  diff % 
 energy_wolf  470,673 (+/- 20663)   495,372 (+/- 105646)        24,699   5.25% 



```



</p></details>

## Individual benchmarks

<details><summary>70c19663 Various fixes</summary>
  <p>





```bash


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf               ... bench:     498,274 ns/iter (+/- 36,929)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf                          ... bench:     747,823 ns/iter (+/- 35,518)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured




```



</p></details>

<details><summary>4893e83e Handle travis CI case inside the script</summary>
  <p>





```bash


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf               ... bench:     495,372 ns/iter (+/- 105,646)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf                          ... bench:     741,668 ns/iter (+/- 11,462)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured




```



</p></details>

<details><summary>3e54b97f Merge pull request #140 from g-bauer/npt_mc_check_global_cutoff</summary>
  <p>





```bash


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf               ... bench:     470,673 ns/iter (+/- 20,663)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 1 test
test energy_wolf                          ... bench:     729,106 ns/iter (+/- 41,502)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured




```



</p></details>

<br>**CPU**: Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz

**Comment by antoinewdg** [comment]
Closing in favor of #143

**Pull request closed without merging**
