### PR TITLE
Enable CI on OS X

### PR DESCRIPTION
**Pull request by Luthaf**
Part of #38.

### CODE REVIEW

**Comment by Luthaf** [comment]
Update: this seems to be blocked on a CMake bug on OS X, for wich I have a workaround in [chemfiles](https://github.com/chemfiles/chemfiles.rs/commit/6f8eb50657e493a5a6305992a9a4ab11b9c3f9d8), that will be included in the next release (hopefully next week).

**Comment by Luthaf** [comment]
I'll merge this tomorrow, if no one has objections! 😄

**Comment by g-bauer** [comment]
Fine with me! 😄

**Comment by antoinewdg** [comment]
Fine with me too.

**Pull request merged**
