### PR TITLE
Add function to compute a molecules' center-of-mass

### PR DESCRIPTION
**Pull request by g-bauer**

### CODE REVIEW

**Comment by Luthaf** [comment]
Looks good to me, we will need to update this when a solution to #18 is found.

Could you also use this function in places where the COM is computed? I believe there is some usage of it in the MC moves, and maybe elsewhere too.

**Comment by g-bauer** [comment]
I know it is used in `Rotate` and I will use it in `Resize`. I will look through the code and add it accordingly.

**Comment by Luthaf** [comment]
And about the coverage limit, it changed in #67, so if you can rebase on top of master, you will get better numbers.

**Comment by g-bauer** [comment]
@Luthaf Do you have more suggestions or can we merge this?

**Comment by Luthaf** [comment]
That was all of it!

**Pull request merged**
