### PR TITLE
Only allow the lj key for Lennard-Jones input

### PR DESCRIPTION
**Pull request by Luthaf**
As discussed in #99.

### CODE REVIEW

**Comment by antoinewdg** [comment]
I solved the merge conflict. I'm thinking this wasn't the best idea ever, in this case it shouldn't matter but I actually think it's better to let the one who opened the PR do it. What's your take on this ?

**Comment by Luthaf** [comment]
> What's your take on this ?

It depends on who is the contributor. For core contributors, we can agree to go for whoever has time to do it, with preference on the one who opened the PR. For occasional contributors that may not be proficient with git, we can help them and fix merge conflicts on the first PR, and ask them to do it on later PRs.

I feels like this is the simplest way, while still being welcoming for external contributors. Does it looks good for you?

**Comment by g-bauer** [comment]
> For occasional contributors that may not be proficient with git, we can help them and fix merge conflicts on the first PR, and ask them to do it on later PRs.

I wholeheartedly second this from my own experience 😄. How did you solve the merge conflict? Is there a way to do this on GitHub directly via the interface?

**Comment by Luthaf** [comment]
> How did you solve the merge conflict? Is there a way to do this on GitHub directly via the interface? 

Yep, this is relatively new: https://github.com/blog/2293-resolve-simple-merge-conflicts-on-github

**Comment by antoinewdg** [comment]
> I feels like this is the simplest way, while still being welcoming for external contributors. Does it looks good for you?

Oh yeah sure if this is to help I don't see why someone else wouldn't do it. My main concern was that if I solve the conflict while you are making changes on your local branch it can get messy.

**Comment by Luthaf** [comment]
git should be able to handle this: if one `git push` but that other commits have been added, there is an error. We can use `git push --force` to overwrite the distant commits, and that is the worst that could happen IMO.

**Comment by antoinewdg** [comment]
Do we squash commits before merging ?

**Comment by Luthaf** [comment]
Yes, we can. there should be an option to do this in the menu near the `Merge pull request` button.

**Pull request merged**
