### PR TITLE
Benchmark all open PRs

### PR DESCRIPTION
**Pull request by antoinewdg**
To launch before going to sleep :)

### CODE REVIEW

**Comment by antoinewdg** [comment]
## Comparing to master (e817acf6)
using `--threshold 2, latest commit first`
<details><summary>4e826864 Benchmark all open PRs</summary>
  <p>





```bash




```



</p></details>

## Individual benchmarks

<details><summary>4e826864 Benchmark all open PRs</summary>
  <p>





```bash


running 4 tests
test argon::cache_move_particle ... bench:     242,474 ns/iter (+/- 1,876)
test argon::energy              ... bench:   1,838,711 ns/iter (+/- 1,782)
test argon::forces              ... bench:   2,353,368 ns/iter (+/- 2,290)
test argon::virial              ... bench:   2,709,489 ns/iter (+/- 7,498)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 8 tests
test nacl::cache_move_particle_ewald ... bench:     409,343 ns/iter (+/- 1,508)
test nacl::cache_move_particle_wolf  ... bench:     107,056 ns/iter (+/- 229)
test nacl::energy_ewald              ... bench:     863,108 ns/iter (+/- 1,945)
test nacl::energy_wolf               ... bench:     470,868 ns/iter (+/- 432)
test nacl::forces_ewald              ... bench:  17,642,941 ns/iter (+/- 37,993)
test nacl::forces_wolf               ... bench:     663,766 ns/iter (+/- 300,529)
test nacl::virial_ewald              ... bench:  48,598,716 ns/iter (+/- 65,513)
test nacl::virial_wolf               ... bench:     661,129 ns/iter (+/- 5,442)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured


running 5 tests
test propane::cache_move_all_rigid_molecules ... bench:   1,033,462 ns/iter (+/- 29,894)
test propane::cache_move_particles           ... bench:     350,622 ns/iter (+/- 878)
test propane::energy                         ... bench:   1,126,895 ns/iter (+/- 5,143)
test propane::forces                         ... bench:   1,382,347 ns/iter (+/- 1,258)
test propane::virial                         ... bench:   1,440,170 ns/iter (+/- 1,511)

test result: ok. 0 passed; 0 failed; 0 ignored; 5 measured


running 10 tests
test water::cache_move_all_rigid_molecules_ewald ... bench:   8,419,220 ns/iter (+/- 59,287)
test water::cache_move_all_rigid_molecules_wolf  ... bench:   8,155,413 ns/iter (+/- 9,013)
test water::cache_move_particles_ewald           ... bench:     862,067 ns/iter (+/- 1,359)
test water::cache_move_particles_wolf            ... bench:     486,757 ns/iter (+/- 717)
test water::energy_ewald                         ... bench:   1,542,431 ns/iter (+/- 2,242)
test water::energy_wolf                          ... bench:     733,239 ns/iter (+/- 1,044)
test water::forces_ewald                         ... bench:  25,809,320 ns/iter (+/- 68,234)
test water::forces_wolf                          ... bench:     992,843 ns/iter (+/- 742)
test water::virial_ewald                         ... bench:  69,962,157 ns/iter (+/- 429,374)
test water::virial_wolf                          ... bench:     986,566 ns/iter (+/- 1,040)

test result: ok. 0 passed; 0 failed; 0 ignored; 10 measured




```



</p></details>

<details><summary>e817acf6 Change the ordering of the arguments</summary>
  <p>





```bash


running 4 tests
test argon::cache_move_particle ... bench:     243,960 ns/iter (+/- 2,219)
test argon::energy              ... bench:   1,838,359 ns/iter (+/- 1,652)
test argon::forces              ... bench:   2,357,078 ns/iter (+/- 4,921)
test argon::virial              ... bench:   2,708,706 ns/iter (+/- 5,807)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 8 tests
test nacl::cache_move_particle_ewald ... bench:     409,026 ns/iter (+/- 2,305)
test nacl::cache_move_particle_wolf  ... bench:     106,300 ns/iter (+/- 151)
test nacl::energy_ewald              ... bench:     863,092 ns/iter (+/- 1,600)
test nacl::energy_wolf               ... bench:     469,527 ns/iter (+/- 660)
test nacl::forces_ewald              ... bench:  17,534,990 ns/iter (+/- 29,940)
test nacl::forces_wolf               ... bench:     664,102 ns/iter (+/- 33,619)
test nacl::virial_ewald              ... bench:  48,222,941 ns/iter (+/- 123,800)
test nacl::virial_wolf               ... bench:     670,158 ns/iter (+/- 1,443)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured


running 5 tests
test propane::cache_move_all_rigid_molecules ... bench:   1,032,675 ns/iter (+/- 27,607)
test propane::cache_move_particles           ... bench:     350,335 ns/iter (+/- 1,945)
test propane::energy                         ... bench:   1,118,108 ns/iter (+/- 1,447)
test propane::forces                         ... bench:   1,388,650 ns/iter (+/- 2,986)
test propane::virial                         ... bench:   1,441,731 ns/iter (+/- 1,368)

test result: ok. 0 passed; 0 failed; 0 ignored; 5 measured


running 10 tests
test water::cache_move_all_rigid_molecules_ewald ... bench:   8,426,788 ns/iter (+/- 54,442)
test water::cache_move_all_rigid_molecules_wolf  ... bench:   8,172,128 ns/iter (+/- 44,858)
test water::cache_move_particles_ewald           ... bench:     860,597 ns/iter (+/- 3,204)
test water::cache_move_particles_wolf            ... bench:     482,055 ns/iter (+/- 2,317)
test water::energy_ewald                         ... bench:   1,541,222 ns/iter (+/- 2,140)
test water::energy_wolf                          ... bench:     735,717 ns/iter (+/- 793)
test water::forces_ewald                         ... bench:  25,756,368 ns/iter (+/- 100,250)
test water::forces_wolf                          ... bench:     992,769 ns/iter (+/- 1,156)
test water::virial_ewald                         ... bench:  70,015,258 ns/iter (+/- 699,385)
test water::virial_wolf                          ... bench:     987,920 ns/iter (+/- 2,834)

test result: ok. 0 passed; 0 failed; 0 ignored; 10 measured




```



</p></details>

<br>**CPU**: Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz

**Comment by Luthaf** [comment]
I am not really convinced by this, as it might get a little spammy, and not all PR needs benchmarking.

How about accepting multiple pr number instead, and launch the script with a multiple PR number before going to sleep?

**Comment by antoinewdg** [comment]
I get your concern, and you are right as it is it's not good. I'm not really convinced by giving multiple PR numbers in input, because what I wanted with this PR is to have something that can be run with minimum effort (i.e. just launching a script), while here one would have to go though the open PRs and choose which one to benchmark.

Maybe a half measure could be a script that benchmarks open PRs only if there have been new commits since the user benchmarked it ?

**Comment by Luthaf** [comment]
Yes, but not all PR needs benchmarking! In fact, most of them don't need benchmarks to run, and this functionality will add needless comments.

What is your use case for this? If it is to run the benchmarks for all the performance PR, how about running the benchmarks for all the PR with the `A-Performance` label?

**Comment by antoinewdg** [comment]
> how about running the benchmarks for all the PR with the A-Performance label?

Yes this can be a solution.

I'm closing this in favor of #151 that implements your first idea, I suggest we just wait a little to see if it's enough before making other changes.

**Pull request closed without merging**
