### PR TITLE
Clippy changes and update author information

### PR DESCRIPTION
**Pull request by Luthaf**
This is a chores PR: 

- Run clippy on the code and change where relevant (1d6e971d9da452732d3dc21d7200f074aeb77f30)
- Add an AUTHORS file following conventions from other projects (64818cf2357cb0112770b1cc6288f8f9430e81c2)
- Update the licence header to mention contributors instead of just me (cd2147a454744b369b77a5b746fb3a3f75fe4225)

@antoinewdg, @g-bauer and @odarbelaeze, do you agree that we put your email in the AUTHORS file (I used `git log --format="%aN <%aE>" | sort | uniq` to generate the list, so the data is already in git), and did I pick the right email?

### CODE REVIEW

**Comment by g-bauer** [comment]
> do you agree that we put your email in the AUTHORS file 

Sure, thanks! Please change my mail address to gernotbauer85@googlemail.com. One day (🙏)  I might leave university ...

**Comment by Luthaf** [comment]
> Sure, thanks! Please change my mail address to gernotbauer85@googlemail.com. One day (🙏) I might leave university ...

Done!

**Comment by antoinewdg** [comment]
No problem for me either, thanks!

**Comment by g-bauer** [comment]
@Luthaf  Do you want to add anything? Else, I'd merge.

**Comment by Luthaf** [comment]
We still need @odarbelaeze to agree. Let's leave him a week to answer before merging.

Anyway, as this PR is touching all files, I think it will be better to rebase it before merging.

**Comment by Luthaf** [comment]
Rebased. I think we can merge it @g-bauer.

**Pull request merged**
