### PR TITLE
Use cargo test --all in travis and in doc

### PR DESCRIPTION
**Pull request by Luthaf**
Support for `cargo test --all` landed in rust 1.15. We can use it for release tests, but debug tests are very slow. instead, we can specify which package to test with `cargo test -p <package>`. It feels more convenient that changing directory all the time, so let's use it in Travis and in contributors documentation.

TODO before merging:
- [x] check that coverage is still OK

### CODE REVIEW

**Comment by antoinewdg** [comment]
It's nice that you fixed the weird warning we discussed at the beginning of #81 .
By the way why has Codecov been disabled ?

**Comment by Luthaf** [comment]
> By the way why has Codecov been disabled ?

No idea ... Looks like the last build that hit codecov was [20 days ago](https://codecov.io/gh/lumol-org/lumol/branches). I'll give it a look tonight.

**Comment by Luthaf** [comment]
Code coverage is working again \o/

**Comment by antoinewdg** [comment]
So what happened ?

**Comment by Luthaf** [comment]
I think I broke it somehow in #91, and the name of the test executables changed with this PR too.

The coverage generation is no longer part of the `after_script` section, but of the `script` section, which means that failing coverage will fail the test, and will not stay unnoticed.

**Comment by Luthaf** [comment]
Do we want to remove the codecov/patch check? It seems it gives a lot of false negatives. Or maybe we can use it only if there is more than 100 lines changed (with a suitable line count threshold).

Also, the code coverage went up again by 3% (yay \o/), I have no idea why (=/). I am explicitly [linking dead code](https://github.com/lumol-org/lumol/blob/4fb238d3d8f745e5de8dfae31a25678e2d9c487f/.travis.yml#L46) here.

Do we want to modify the threshold for codecov/project then?

**Pull request merged**
