### PR TITLE
Move docs to sphinx

### PR DESCRIPTION
**Pull request by g-bauer**
This PR tackles #211 

# Issues

- Latex can't use `svg`file format for images.

### CODE REVIEW

**Comment by Luthaf** [comment]
Sorry, I did not had the time to look at this this weekend. I'll try to do it during the week, I should have a bit more time =)

**Comment by Luthaf** [comment]
I moved stuff around a bit, the diff might be hard to read ... =/

But I like the structure here, tell me what you think! 

A remaining question concerning organisation is should there be two separated sphinx projects for the user manual and the input reference? Having the input reference as a (well separated) section of the user manual have some advantages:

- Cross-linking (from the tutorials to the reference for example) would be easier
- Only one link to visit/PDF to download for the users. We already have API doc in a separated place, I'd rather not fragment the doc even more.

**Comment by Luthaf** [comment]
From #211:

- [ ] Convert tfrom mdbook to sphinx
    - [ ] Convert the user manual to sphinx (`doc/src/concepts`) + FAQ + Installation + introduction;
    - [ ] Convert the tutorials to sphinx (`doc/src/tutorials`);
    - [ ] Convert the advanced tutorials to sphinx (`doc/src/advanced`);
- [ ] Build the sphinx manual on travis
    - [ ] Setup requirements.txt and a Readme about how to build the doc
    - [ ] Build the doc on Travis
    - [ ] Deploy the built HTML doc on Github pages
    - [ ] Also deploy the built PDF doc on Github pages?
- [ ] Remove the previous doc

**Comment by g-bauer** [comment]
We could move move the input reference into the book. I think if one regularly uses the code, the input reference is the primary source one needs. So it should be easily accessible inside the book.

> But I like the structure here, tell me what you think!

I think the structure is really good now. Also, the literal includes are awesome. I am not sure I'm liking it that all `html` files reside next to the `rst` files though. Makes the whole directory very cluttered.

I corrected some typos and made some small changes to formulations. If you are ok with these changes, I'd say we (you) merge this state. We can pull in the input and build the configuration for CI in another PR while we are not blocking the docs for other PRs.

**Comment by Luthaf** [comment]
> I think the structure is really good now. Also, the literal includes are awesome. I am not sure I'm liking it that all html files reside next to the rst files though. Makes the whole directory very cluttered.

I am not sure I understand what you say here. There should not be any HTML file around in the doc/ directory, right ?

**Comment by g-bauer** [comment]
Oops! I think that might have happened when I pulled the changes. I had the html files sitting next to the rst files after pulling your changes, dunno why. All good, I removed them 😄 Sorry!

**Comment by Luthaf** [comment]
> I had the html files sitting next to the rst files after pulling your changes, dunno why

Maybe the previous build that was no longer in `.gitignore`?

**Comment by Luthaf** [comment]
I added HTML generation on CI and merged the reference in the manual.

The last remaining item from the TODO list (building and publishing PDF) will come later, as I think it can require some fiddling around with Travis settings. If Travis passes, we can merge this!

**Pull request merged**
