### PR TITLE
Integrate the approx crate

### PR DESCRIPTION
**Pull request by antoinewdg**
What this PR does:
* add the [approx](https://crates.io/crates/approx) crate to dependencies
* implement the `ApproxEq` trait for `Vector3D`
* changes some assertions in existing tests on Vector3D
* changes the problematic assertions mentionned in #107 

He are the guidelines I suggest for floating point comparison (feedback appreciated): 
* when we want two floats (are structs involving floats such as `Vector3D`) to be exactly equal in theory but they are not due two float imprecision, we use `assert_ulps_eq!` with default parameters
* when we want two floats to be close but expect them to be a little different (such as when testing that energy remains constant) we use `assert_relative_eq!` and play with the `max_relative` parameter to allow more or less error
* we never ever use `assert_eq!` for anything that has a float in it

### CODE REVIEW

**Comment by Luthaf** [comment]
> He are the guidelines I suggest for floating point comparison (feedback appreciated):

These seems sensible guidelines for me. Can we have some kind of lint/tool to enforce "we never ever use assert_eq! for anything that has a float in it"?


Can we remove the `assert_approx_eq` macro completely and replace it by the `assert_ulps_eq`  everywhere?

**Comment by antoinewdg** [comment]
> Can we remove the assert_approx_eq macro completely and replace it by the assert_ulps_eq everywhere?

We could, but what we would actually need to do is look at every single use of `assert_approx_eq` and think about if we want to use `assert_ulps_eq` or `assert_relative_eq`. I'm looking into doing it, this may be a bit long.

> Can we have some kind of lint/tool to enforce "we never ever use assert_eq! for anything that has a float in it"?

I have no idea about that, but we would have to be sure that we fix the old code before setting this up.

It turns out that having to type the `max_relative` parameter for the `assert_relative_eq!` is a bit too verbose, I suggest we create a new macro `assert_percentage_eq` that just takes the percentage as a parameter (it could also take a real percentage as a parameter instead of a number between 0 and 1), what do you think ?

**Comment by Luthaf** [comment]
> We could, but what we would actually need to do is look at every single use of assert_approx_eq and think about if we want to use assert_ulps_eq or assert_relative_eq. 

Can you have a look and do the one you know in which category they fall, and I'll do the remaining ones.

> I suggest we create a new macro assert_percentage_eq that just takes the percentage as a parameter (it could also take a real percentage as a parameter instead of a number between 0 and 1), what do you think ?

Yes, why not.

**Comment by Luthaf** [comment]
I found the time to finish this, now `assert_approx_eq!` is gone ! I'll merge it tomorrow if nobody has an objection.

**Pull request merged**
