### PR TITLE
Update dependencies for parallelization

### PR DESCRIPTION
**Pull request by antoinewdg**
I'm going to start breaking down #131 into smaller PRs to make reviews easier. This will be the starting point of all the PRs once merged.

### CODE REVIEW

**Comment by antoinewdg** [comment]
## Comparing to master (e97e92a6)
using `--threshold 2, latest commit first`
<details><summary>e0cff46e Update dependencies for parallelization</summary>
  <p>





```bash

 name                                         e97e92a6.txt ns/iter    e0cff46e.txt ns/iter   diff ns/iter  diff % 
 propane::virial                              1,443,740 (+/- 1135)    1,512,294 (+/- 7684)         68,554   4.75% 
 water::cache_move_all_rigid_molecules_ewald  8,633,080 (+/- 125174)  8,415,842 (+/- 21863)      -217,238  -2.52% 
 water::cache_move_all_rigid_molecules_wolf   8,319,140 (+/- 15029)   8,133,566 (+/- 26786)      -185,574  -2.23% 



```



</p></details>

## Individual benchmarks

<details><summary>e0cff46e Update dependencies for parallelization</summary>
  <p>





```bash


running 4 tests
test argon::cache_move_particle ... bench:     242,872 ns/iter (+/- 607)
test argon::energy              ... bench:   1,850,181 ns/iter (+/- 4,858)
test argon::forces              ... bench:   2,356,214 ns/iter (+/- 5,701)
test argon::virial              ... bench:   2,711,596 ns/iter (+/- 4,209)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 8 tests
test nacl::cache_move_particle_ewald ... bench:     408,249 ns/iter (+/- 586)
test nacl::cache_move_particle_wolf  ... bench:     106,140 ns/iter (+/- 522)
test nacl::energy_ewald              ... bench:     617,983 ns/iter (+/- 1,517)
test nacl::energy_wolf               ... bench:     473,167 ns/iter (+/- 2,225)
test nacl::forces_ewald              ... bench:  17,245,777 ns/iter (+/- 27,416)
test nacl::forces_wolf               ... bench:     665,175 ns/iter (+/- 1,014)
test nacl::virial_ewald              ... bench:  48,284,138 ns/iter (+/- 437,381)
test nacl::virial_wolf               ... bench:     662,610 ns/iter (+/- 928)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured


running 5 tests
test propane::cache_move_all_rigid_molecules ... bench:   1,029,977 ns/iter (+/- 12,378)
test propane::cache_move_particles           ... bench:     281,278 ns/iter (+/- 10,684)
test propane::energy                         ... bench:   1,111,198 ns/iter (+/- 1,580)
test propane::forces                         ... bench:   1,397,735 ns/iter (+/- 26,162)
test propane::virial                         ... bench:   1,512,294 ns/iter (+/- 7,684)

test result: ok. 0 passed; 0 failed; 0 ignored; 5 measured


running 10 tests
test water::cache_move_all_rigid_molecules_ewald ... bench:   8,415,842 ns/iter (+/- 21,863)
test water::cache_move_all_rigid_molecules_wolf  ... bench:   8,133,566 ns/iter (+/- 26,786)
test water::cache_move_particles_ewald           ... bench:     855,472 ns/iter (+/- 2,125)
test water::cache_move_particles_wolf            ... bench:     481,602 ns/iter (+/- 2,239)
test water::energy_ewald                         ... bench:   1,018,108 ns/iter (+/- 3,045)
test water::energy_wolf                          ... bench:     730,773 ns/iter (+/- 1,324)
test water::forces_ewald                         ... bench:  24,936,408 ns/iter (+/- 50,982)
test water::forces_wolf                          ... bench:     999,764 ns/iter (+/- 3,342)
test water::virial_ewald                         ... bench:  69,746,748 ns/iter (+/- 754,336)
test water::virial_wolf                          ... bench:     997,216 ns/iter (+/- 7,203)

test result: ok. 0 passed; 0 failed; 0 ignored; 10 measured




```



</p></details>

<details><summary>e97e92a6 Adds rotation matrix as method of Matrix3.</summary>
  <p>





```bash


running 4 tests
test argon::cache_move_particle ... bench:     243,139 ns/iter (+/- 2,416)
test argon::energy              ... bench:   1,848,334 ns/iter (+/- 2,661)
test argon::forces              ... bench:   2,355,249 ns/iter (+/- 6,074)
test argon::virial              ... bench:   2,716,856 ns/iter (+/- 29,662)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured


running 8 tests
test nacl::cache_move_particle_ewald ... bench:     407,720 ns/iter (+/- 973)
test nacl::cache_move_particle_wolf  ... bench:     106,258 ns/iter (+/- 390)
test nacl::energy_ewald              ... bench:     625,994 ns/iter (+/- 1,305)
test nacl::energy_wolf               ... bench:     472,953 ns/iter (+/- 581)
test nacl::forces_ewald              ... bench:  17,326,814 ns/iter (+/- 47,576)
test nacl::forces_wolf               ... bench:     665,383 ns/iter (+/- 1,498)
test nacl::virial_ewald              ... bench:  48,398,721 ns/iter (+/- 58,031)
test nacl::virial_wolf               ... bench:     662,030 ns/iter (+/- 1,702)

test result: ok. 0 passed; 0 failed; 0 ignored; 8 measured


running 5 tests
test propane::cache_move_all_rigid_molecules ... bench:   1,029,507 ns/iter (+/- 13,446)
test propane::cache_move_particles           ... bench:     280,655 ns/iter (+/- 10,795)
test propane::energy                         ... bench:   1,110,980 ns/iter (+/- 2,264)
test propane::forces                         ... bench:   1,379,622 ns/iter (+/- 2,226)
test propane::virial                         ... bench:   1,443,740 ns/iter (+/- 1,135)

test result: ok. 0 passed; 0 failed; 0 ignored; 5 measured


running 10 tests
test water::cache_move_all_rigid_molecules_ewald ... bench:   8,633,080 ns/iter (+/- 125,174)
test water::cache_move_all_rigid_molecules_wolf  ... bench:   8,319,140 ns/iter (+/- 15,029)
test water::cache_move_particles_ewald           ... bench:     852,840 ns/iter (+/- 3,709)
test water::cache_move_particles_wolf            ... bench:     480,628 ns/iter (+/- 1,427)
test water::energy_ewald                         ... bench:   1,016,218 ns/iter (+/- 2,865)
test water::energy_wolf                          ... bench:     730,666 ns/iter (+/- 1,761)
test water::forces_ewald                         ... bench:  24,850,615 ns/iter (+/- 41,080)
test water::forces_wolf                          ... bench:     999,924 ns/iter (+/- 2,496)
test water::virial_ewald                         ... bench:  69,775,450 ns/iter (+/- 827,755)
test water::virial_wolf                          ... bench:     993,450 ns/iter (+/- 3,906)

test result: ok. 0 passed; 0 failed; 0 ignored; 10 measured




```



</p></details>

<br>**CPU**: Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz

**Comment by Luthaf** [comment]
This is a bit strange: this PR adds unused dependencies only. I feel like it should come with some code too.

**Comment by antoinewdg** [comment]
Well the goal is to have it as a starting point for my next PRs. I'm doing this because I want to be able to work on multiple PRs that would use these dependencies, and having PRs that depend on each other is a mess. 
This one is here just because it is easy to review and quick to merge, and then every PR on parallelization can just branch from master and be independent from each other.

**Comment by Luthaf** [comment]
OK, I get it =)

**Pull request merged**
