### PR TITLE
Only accept integers as 'every' in controls

### LINKED ISSUE #31: Ability to run control algorithm not at all steps
Control algorithms like `RemoveRotation` and `RemoveTranslation` do not need to run at each simulation step. they could have separated frequency field to run them only every so often.

### PR DESCRIPTION
**Pull request by Luthaf**
Ref #84 and fix #31 !

### CODE REVIEW

**Comment by antoinewdg** [comment]
Seems good to me.

**Comment by Luthaf** [comment]
> Seems good to me.

You can hit the merge button then! 😉

**Comment by antoinewdg** [comment]
I'm almost sure the answer is yes, but better safe than sorry: do I delete the branch ?

**Comment by g-bauer** [comment]
Yepp!

**Comment by Luthaf** [comment]
> Yepp! Oh wait ... I let the PR initiator delete it in the past. What's the right thing to do?

I don't really care here =) If everyone is OK with it we can settle on using one branch for one PR only, and delete them when merging.

Also, when creating branches on this repo (lumol-org/lumol), we might want to use some kind of namespacing scheme (i.e. this branch should be named `luthaf/every`) to prevent conflicts.

**Pull request merged**
